### ISSUE TITLE
Add some leetcode questions

### ISSUE THREAD

**Issue by khushimarothi** [tushar-kumar/HacktoberFest2022#2]
I want to add leetcode medium level question.
question no.- 7. Reverse integer
43. Multiply strings
Please assign the issue and add hactoberfest labels.

**Comment by Aman-Sekhon** [comment]
Hello, I would like o contribute to the repo... Can I?

**Comment by abhayanand08** [comment]
hey @tushar-kumar  i would like to add some awesome questions to this issue. Please assign this issue to me

**Comment by ankit-singh02** [comment]
Can you assign this issue to me for hacktoberfest

**Comment by rittik29** [comment]
can you assign me this issue so i can contribute

**Comment by rittik29** [comment]
i have contributed to your repository kindly please merge my pull request @tushar-kumar
