### ISSUE TITLE
Merge Sort and Quick Sort algorithm

### ISSUE THREAD

**Issue by RishabhSrivastava1423** [tushar-kumar/HacktoberFest2022#31]
I want to add Merge sort and Quick sort algorithm.
 Please assign this to me so that I may contribute my code as part of Hacktoberfest 2022.

**Comment by Utkarsh2312** [comment]
I am a Competitive Programming enthusiasts. I would like to contribute in your repository. Can you please assign this task to me under Hacktober fest 2022 label.

**Comment by garvit0908** [comment]
Hello this is my first try in Hacktoberfest .Kindly assign me this issue so that i can also make contribution in open source

**Comment by Saaraansh10** [comment]
Can you please assign this task to me @tushar-kumar ?

**Comment by ManasiGDeshmukh** [comment]
Hey
I'm Manasi Deshmukh
SY computer Engineering
Can you please assign me this issue??
